### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by neurotoxinvx** [simonhao/made-build#1]
I think maybe the 'src' & 'dist' move to the main folder more better,and add the scripts 'npm run dev' & 'npm run build'.
:)

**Comment by simonhao** [comment]
你说的是test下面的吗？那是个测试用例。如果你需要使用made-build的话，应该使用 npm install -g 来安装，之后会有全局的mb命令来使用。而你的工程目录就类似test下面那样，src 和 conf。这个地方还差点文档，你要不来搞搞？

**Comment by neurotoxinvx** [comment]
正研究着呢，去你scripts就看到了test命令没找到run的方法哈，我去看看源码

**Comment by simonhao** [comment]
test命令可以通过npm test来启动。
